# Generated by Django 3.0.8 on 2020-08-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_userposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='network.UserProfile'),
        ),
    ]
