# Generated by Django 3.0.8 on 2020-08-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_userposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposts',
            name='owner',
        ),
        migrations.AddField(
            model_name='userposts',
            name='owner',
            field=models.ManyToManyField(related_name='owner', to='network.UserProfile'),
        ),
    ]
