# Generated by Django 3.0.8 on 2020-08-15 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20200815_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
