# Generated by Django 3.0.8 on 2020-08-15 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200815_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposts',
            name='owner',
        ),
        migrations.AddField(
            model_name='userposts',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='network.UserProfile'),
            preserve_default=False,
        ),
    ]
