# Generated by Django 3.0.8 on 2020-08-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20200815_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposts',
            name='timestamp',
        ),
    ]
