# Generated by Django 3.0.8 on 2020-08-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_userposts_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPosts',
        ),
    ]
