# Generated by Django 3.0.8 on 2020-08-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20200815_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
