# Generated by Django 3.0.8 on 2020-08-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20200815_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposts',
            name='timestamp',
        ),
    ]
