# Generated by Django 3.0.8 on 2020-08-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_remove_userposts_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPosts',
        ),
    ]
