# Generated by Django 3.0.8 on 2020-08-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_delete_userposts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
