# Generated by Django 3.0.8 on 2020-08-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_auto_20200823_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
