# Generated by Django 3.0.8 on 2020-08-28 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_likedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedpost',
            name='postowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postowner', to=settings.AUTH_USER_MODEL),
        ),
    ]
