# Generated by Django 3.0.8 on 2020-08-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0029_auto_20200830_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessageclass',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
