# Generated by Django 3.0.8 on 2020-09-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0031_directmessageclass_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessageclass',
            name='reply',
        ),
    ]
